In [95]:
import pandas as pd 
import numpy as np 
import pprint

In [96]:
df = pd.read_csv('dataset.csv')
df.sample(4)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
75790,75790,2SIgGbcduNKHTFEFcvmUaS,Deuter,Koyasan: Reiki Sound Healing,Sound of Invisible Waters,50,572853,False,0.111,0.0211,...,-26.997,0,0.0384,0.956,0.97400,0.0617,0.0362,56.653,3,new-age
18625,18625,14KRQPqBGbMHKheHc31Xdm,Tom Papa,Human Mule,Saving the World,21,166810,False,0.671,0.5970,...,-15.384,1,0.9540,0.730,0.00000,0.7210,0.3790,51.654,4,comedy
102284,102284,4ZRs2BzVlK54h1GyZO799I,Paolo Nutini,Human - Best Adult Pop Tunes,Numpty,0,234066,True,0.839,0.4410,...,-9.024,1,0.0499,0.727,0.00001,0.1100,0.8970,123.007,4,songwriter
105529,105529,6tw6f2SpScnkWeFMzc9Ykd,Beat Oven,Kid Tested & Mother Approved,The Feels,32,102250,False,0.587,0.4070,...,-12.168,0,0.0330,0.699,0.89500,0.1070,0.5130,79.974,4,study

In [97]:
df.duplicated(subset=["track_id"]).sum()

np.int64(24259)

In [98]:
df.drop_duplicates(subset= ['track_id'],inplace= True)

In [99]:
(df.select_dtypes('str')).columns.tolist()

['track_id', 'artists', 'album_name', 'track_name', 'track_genre']

In [100]:
df.duplicated(subset=['artists', 'track_name','explicit']).sum()

np.int64(8319)

In [101]:
df[df.duplicated(subset=['artists', 'track_name','explicit'])].head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
18,18,2qLMf6TuEC3ruGJg4SMMN6,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,68,189613,False,0.625,0.414,...,-8.700,1,0.0369,0.294,0.000000,0.1510,0.6690,130.088,4,acoustic
20,20,3S0OXQeoh0w6AY8WQVckRW,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,75,242946,False,0.703,0.444,...,-9.331,1,0.0417,0.559,0.000000,0.0973,0.7120,150.960,4,acoustic
22,22,5TvE3pk05pyFIGdSY9j4DJ,A Great Big World;Christina Aguilera,Is There Anybody Out There? - Track by Track C...,Say Something,70,229400,False,0.407,0.147,...,-8.822,1,0.0355,0.857,0.000003,0.0913,0.0765,141.284,3,acoustic
28,28,5QAMZTM5cmLg3fHX9ZbTZi,Jason Mraz,Christmas Time,Winter Wonderland,0,131760,False,0.620,0.309,...,-9.209,1,0.0495,0.788,0.000000,0.1460,0.6640,145.363,4,acoustic
29,29,2qESE1ZeWly7I3YjyTXmXh,Jason Mraz,Perfect Christmas Hits,Winter Wonderland,0,131760,False,0.620,0.309,...,-9.209,1,0.0495,0.788,0.000000,0.1460,0.6640,145.363,4,acoustic

In [102]:
df.drop_duplicates(subset=['artists', 'track_name','explicit'],inplace= True )

In [103]:
df.shape

(81422, 21)

In [104]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [105]:
df=df.dropna()

In [106]:
df.info()

<class 'pandas.DataFrame'>
Index: 81421 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        81421 non-null  int64
 1   track_id          81421 non-null  str
 2   artists           81421 non-null  str
 3   album_name        81421 non-null  str
 4   track_name        81421 non-null  str
 5   popularity        81421 non-null  int64
 6   duration_ms       81421 non-null  int64
 7   explicit          81421 non-null  bool
 8   danceability      81421 non-null  float64
 9   energy            81421 non-null  float64
 10  key               81421 non-null  int64
 11  loudness          81421 non-null  float64
 12  mode              81421 non-null  int64
 13  speechiness       81421 non-null  float64
 14  acousticness      81421 non-null  float64
 15  instrumentalness  81421 non-null  float64
 16  liveness          81421 non-null  float64
 17  valence           81421 non-null  float64
 18  tempo             81421 non-null  float64
 19  time_signature    81421 non-null  int64
 20  track_genre       81421 non-null  str
dtypes: bool(1), float64(9), int64(6), str(5)
memory usage: 19.8 MB

In [107]:
len(df['track_id'].unique())

81421

In [108]:
XO = []
for i,s in enumerate(df['artists']):
    if 'The Weeknd' in s:
        s = df.iloc[i]['track_name']
        XO.append(s)
pprint.pprint(set(XO))

{'After Hours',
 'Blinding Lights',
 'Call Out My Name',
 'Die For You',
 'Hawái - Remix',
 'I Feel It Coming',
 'I Was Never There',
 'Lost in the Fire (feat. The Weeknd)',
 'Love Me Harder',
 'Make It (feat. The Weeknd) [DJAmg Remixer]',
 'Moth To A Flame',
 'Moth To A Flame (feat. The Weeknd) - Adriatique Remix',
 'Moth To A Flame (with The Weeknd)',
 'Moth To A Flame (with The Weeknd) - Extended Mix',
 'Moth To A Flame (with The Weeknd, Moojo) - Moojo Remix',
 'Odd Look',
 'Or Nah (feat. The Weeknd, Wiz Khalifa & DJ Mustard) - Remix',
 'Or Nah - Remix',
 'Out of Time',
 'Over Now (with The Weeknd)',
 'Save Your Tears',
 'Starboy',
 'Take My Breath - Single Version',
 'Tears In The Club (feat. The Weeknd)',
 'The Hills',
 'You Right',
 'tears in the club',
 'tears in the club (feat. the weeknd)'}

In [109]:
# df = df.reset_index(drop=True)

In [110]:
df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='str')

In [111]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [112]:
df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [113]:
df.drop(columns = {'popularity', 'duration_ms', 'album_name'}, inplace = True)

In [114]:
data = [ 'danceability',	'energy',	'key',	'loudness'	,'mode',	'speechiness'	,'acousticness',	'instrumentalness',	'liveness',	'valence',	'tempo',	'time_signature']

In [115]:
meta_data = df[data]

In [116]:
# meta_data = np.array(meta_data)

In [117]:
df.drop(columns = data ,inplace =True)

In [118]:
df.head()

,track_id,artists,track_name,explicit,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,False,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost - Acoustic,False,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,False,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Can't Help Falling In Love,False,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,False,acoustic

In [119]:
# df.rename(columns={'track_name':'song'},inplace = True)

In [120]:
for col in df.select_dtypes(include = ['str']).columns:
    if col == 'track_id':
        continue
    df[col] = df[col].str.strip().str.lower()

In [121]:
df.head()

,track_id,artists,track_name,explicit,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,gen hoshino,comedy,False,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,ben woodward,ghost - acoustic,False,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,ingrid michaelson;zayn,to begin again,False,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,kina grannis,can't help falling in love,False,acoustic
4,5vjLSffimiIP26QG5WcN2K,chord overstreet,hold on,False,acoustic

In [122]:
len(df['track_genre'].unique())

113

In [123]:
df['artists']

0                    gen hoshino
1                   ben woodward
2         ingrid michaelson;zayn
3                   kina grannis
4               chord overstreet
                   ...
113995             rainy lullaby
113996             rainy lullaby
113997             cesária evora
113998          michael w. smith
113999             cesária evora
Name: artists, Length: 81421, dtype: str

In [124]:
df['tags'] = df['artists']+ ' ' +df['track_genre']

In [125]:
df['artists'] = df['artists'].str.split(';')

In [126]:
df.head()

,track_id,artists,track_name,explicit,track_genre,tags
0,5SuOikwiRyPMVoIQDJUgSV,[gen hoshino],comedy,False,acoustic,gen hoshino acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,[ben woodward],ghost - acoustic,False,acoustic,ben woodward acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,"[ingrid michaelson, zayn]",to begin again,False,acoustic,ingrid michaelson;zayn acoustic
3,6lfxq3CG4xtTiEg7opyCyx,[kina grannis],can't help falling in love,False,acoustic,kina grannis acoustic
4,5vjLSffimiIP26QG5WcN2K,[chord overstreet],hold on,False,acoustic,chord overstreet acoustic

In [127]:
df[df.duplicated(subset=[ 'track_name','tags','explicit'])]

,track_id,artists,track_name,explicit,track_genre,tags
70,16dkWKIlBsfYTISCVuDs0w,[ron pope],a drop in the ocean,False,acoustic,ron pope acoustic
190,0v0pc1lIt5p6EBX7pnfOGF,[ross copperman],holding on and letting go,False,acoustic,ross copperman acoustic
876,2vP0JcTiuYnzrBy45ACKBz,[keisha white],the weakness in me,False,acoustic,keisha white acoustic
1992,33dYPQCYUztZKUJqmyQR6L,[william onyeabor],the moon and the sun,False,afrobeat,william onyeabor afrobeat
2161,5WTKiRTdoDk07YJOP7y8DU,[kaleo],way down we go,False,alt-rock,kaleo alt-rock
...,...,...,...,...,...,...
111636,6yoqKyNAJOjTlFnDM8u6Ka,[boozoo bajou],night over manaus,False,trip-hop,boozoo bajou trip-hop
113574,0k3H456t5wd6kkje7MTarL,[hillsong worship],shout to the lord,False,world-music,hillsong worship world-music
113649,7MzEigadl6tP6TmaxagWNt,[hillsong worship],worthy is the lamb,False,world-music,hillsong worship world-music
113708,1jLAfwuB7v9lBdwDcJF39G,[phil wickham],house of the lord,False,world-music,phil wickham world-music
113946,5XTdgvMiVHNSzzFrKAXU91,[cesária evora],petit pays,False,world-music,cesária evora world-music

In [128]:
df['tags']

0                    gen hoshino acoustic
1                   ben woodward acoustic
2         ingrid michaelson;zayn acoustic
3                   kina grannis acoustic
4               chord overstreet acoustic
                       ...
113995          rainy lullaby world-music
113996          rainy lullaby world-music
113997          cesária evora world-music
113998       michael w. smith world-music
113999          cesária evora world-music
Name: tags, Length: 81421, dtype: str

In [129]:
df = df.reset_index(drop=True)

https://huggingface.co/sentence-transformers

In [130]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7757.75it/s]

In [131]:
%%time
tag_embeddings = model.encode(df['tags'].tolist(), normalize_embeddings = True)

CPU times: user 16.8 s, sys: 3.23 s, total: 20.1 s
Wall time: 10.8 s

In [132]:
tag_embeddings

array([[-0.08406793,  0.06625666, -0.00450069, ...,  0.01489832,
        -0.01095574,  0.00164438],
       [-0.0499217 , -0.02553014,  0.0193305 , ...,  0.003179  ,
        -0.03412907, -0.03640854],
       [-0.11297348, -0.04440821, -0.02443785, ..., -0.04375131,
         0.05449506, -0.03858234],
       ...,
       [-0.000725  , -0.0265787 , -0.01766037, ..., -0.02808608,
         0.0374263 , -0.04857159],
       [-0.05028116,  0.01812024,  0.00465453, ...,  0.00109861,
         0.01093575, -0.0654993 ],
       [-0.000725  , -0.0265787 , -0.01766037, ..., -0.02808608,
         0.0374263 , -0.04857159]], shape=(81421, 384), dtype=float32)

In [133]:
from sklearn.preprocessing import StandardScaler, normalize

In [134]:
sc = StandardScaler()

In [135]:
meta_data

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4
1,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4
2,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4
3,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3
4,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4
...,...,...,...,...,...,...,...,...,...,...,...,...
113995,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5
113996,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4
113997,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4
113998,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4
113999,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4

In [136]:
audio_data = sc.fit_transform(meta_data)

In [137]:
audio_data = normalize (audio_data)

In [138]:
audio_data.shape, tag_embeddings.shape

((81421, 12), (81421, 384))

In [139]:
merged = np.concatenate([audio_data, tag_embeddings], axis = 1)

In [140]:
merged = normalize(merged)

In [141]:
audio_data.max()

np.float64(0.953764520770774)

In [142]:
df.head()

,track_id,artists,track_name,explicit,track_genre,tags
0,5SuOikwiRyPMVoIQDJUgSV,[gen hoshino],comedy,False,acoustic,gen hoshino acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,[ben woodward],ghost - acoustic,False,acoustic,ben woodward acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,"[ingrid michaelson, zayn]",to begin again,False,acoustic,ingrid michaelson;zayn acoustic
3,6lfxq3CG4xtTiEg7opyCyx,[kina grannis],can't help falling in love,False,acoustic,kina grannis acoustic
4,5vjLSffimiIP26QG5WcN2K,[chord overstreet],hold on,False,acoustic,chord overstreet acoustic

In [143]:
def score(song, all_song):
    return song @ all_song

In [144]:
df.shape

(81421, 6)

In [145]:
df.sample(5)

,track_id,artists,track_name,explicit,track_genre,tags
14551,6RYmlLkbx5ZAbOjKDqXEzp,"[wolfgang amadeus mozart, danielle laval]","8 variations on ""laat ons juichen"" by c.e. gra...",False,classical,wolfgang amadeus mozart;danielle laval classical
46254,2tBO9sDqez1uQYsb8EYkjx,[sabke morde],seebe sorkh,False,iranian,sabke morde iranian
45456,2PgaoRDmiqMMgqgTIfue4u,[kmfdm],search & destroy,False,industrial,kmfdm industrial
5765,3337Hpv6XBBEWLwoRsSMxT,[tersivel],cruzat beer house song,False,black-metal,tersivel black-metal
78062,6ssqfhhoK0uLambmUXMbIA,[die atzen],diss is nice,True,techno,die atzen techno

In [146]:
type(df['artists'].iloc[0])

list

In [147]:
merged.T.shape

(396, 81421)

In [148]:
ind = np.argsort(score(merged[81004].reshape(1,-1), merged.T).flatten())[-6:-1][::-1]
ind

array([80936, 81373, 80971, 81051, 80963])

In [149]:
df.iloc[81004]

track_id          6TyyGSk69X8S922AF5L4qE
artists                  [shane & shane]
track_name                  living water
explicit                           False
track_genre                  world-music
tags           shane & shane world-music
Name: 81004, dtype: object

In [150]:
for i in ind :
    print(df.iloc[i])

track_id          1SnZi2eVU2kcXRNJT6ek4J
artists                  [shane & shane]
track_name            how great thou art
explicit                           False
track_genre                  world-music
tags           shane & shane world-music
Name: 80936, dtype: object
track_id          4JDmqxJrJS9FoMPzWmILkQ
artists                  [shane & shane]
track_name      psalm 34 (taste and see)
explicit                           False
track_genre                  world-music
tags           shane & shane world-music
Name: 81373, dtype: object
track_id         7wBs0H1Ebr1h14Qqm43KiO
artists                  [chris tomlin]
track_name                   white flag
explicit                          False
track_genre                 world-music
tags           chris tomlin world-music
Name: 80971, dtype: object
track_id         4Upx1mXplDCRQKpnF64KXc
artists                  [chris tomlin]
track_name               great forgiver
explicit                          False
track_genre                 world-music
tags           chris tomlin world-music
Name: 81051, dtype: object
track_id                         2Zxili8AmCuqiomg9HzTgH
artists                                 [shane & shane]
track_name     psalm 23 (surely goodness, surely mercy)
explicit                                          False
track_genre                                 world-music
tags                          shane & shane world-music
Name: 80963, dtype: object

In [151]:
np.argsort(score(merged[20100].reshape(1,-1),merged.T).flatten())[::-1]

array([20100, 20046, 20241, ..., 58777, 26877, 58602], shape=(81421,))

In [152]:
import re

In [153]:
def get_similar_song(song_name = None, artist_name = None, Explicit = True):
    result = []
    track = song_name

    
    if  artist_name:
        artist_name = artist_name.lower().strip()
        artist_name = df['artists'].apply(lambda a : artist_name in a )
    else :
        artist_name = pd.Series(True, index=df.index)
        
    if song_name:
        song_name = song_name.lower().strip()
        song_name = df['track_name'].str.contains(rf"\b{re.escape(song_name.strip())}\b",regex=True)
    else:
        song_name = pd.Series(True, index=df.index)
        
    # Indexing and song extraction 
    res = song_name & artist_name 
        
    if not res.any():
        return "No matching song found."
    
    if not track:
        query_mat = merged[res].mean(axis=0)
    else:
        song_ind = df[res].index[0]
        query_mat = merged[song_ind]
    
    score = np.argsort(query_mat.reshape(1,-1)@ merged.T).flatten()[::-1]
    
    for i in score:
        if not Explicit :
            if df.iloc[i]['explicit']:
                continue
        sng = df.iloc[i]['track_name']
        if sng == track: # skipping the querry song
            continue
        
        art = df.iloc[i]['artists'] 
        link = df.iloc[i]['track_id']
        if ((sng,art)) not in result:
            result.append((link, sng, art))
        if len(result)==10:
            break
    
    result =  [result[i] for i in (np.random.choice(10, replace = False, size= 5 ))]
    result = pd.DataFrame(result, columns = ['Link', "Song", "Artist(s)"])
    return result

In [154]:
get_similar_song()

,Link,Song,Artist(s)
0,7pqp5R4GY8HTaAbpAGZJFb,彼女はブルー,[shogo hamada]
1,3SatS51LrCRNkQN1quaB7W,si me ves,[cadena perpetua]
2,3qwQ3PEudWSXRaWbsJUUx5,stay - jonas blue remix,"[zedd, alessia cara, jonas blue]"
3,1xVviGd6Y0zujEmjiTzdiL,fruta amarga,[karamelo santo]
4,0kuL28JVeWVO86sXrCYFar,los cangrejos,[karamelo santo]

In [155]:
get_similar_song(artist_name='the weeknd')

,Link,Song,Artist(s)
0,0MnmtOOke4uQVBMAjIgwVZ,after hours,[the weeknd]
1,0VO8gYVDSwM1Qdd2GsMoYK,moth to a flame (with the weeknd),"[swedish house mafia, the weeknd]"
2,2Ch7LmS7r2Gy2kc64wv3Bz,die for you,[the weeknd]
3,5XCa3ygRyz2R9avSi0CYJI,i feel it coming,"[the weeknd, daft punk]"
4,0VjIjW4GlUZAMYd2vXMi3b,blinding lights,[the weeknd]

In [156]:
df[df['track_name']=='the hills']

,track_id,artists,track_name,explicit,track_genre,tags
14859,7yF0tjZPXO9x4v0M9U6VQy,[kloud],the hills,False,club,kloud club
61331,4g7118rCobKcU4XQXSFlBS,[the weeknd],the hills,True,pop,the weeknd pop

In [157]:
import joblib
np.save('merged_mat.npy',merged)
joblib.dump(df,'df.pkl')

['df.pkl']

In [160]:
s='  '
s.strip()

''